### ISSUE TITLE
is this project real?

### ISSUE THREAD

**Issue by tjwebb** [alayton/extraload#2]
all the documentation links to empty files

**Comment by wingmanzz** [comment]
haha, i found this project too. have you tried it?

**Comment by tjwebb** [comment]
Hey man. No I ended up building some tools myself for Postgres:

https://github.com/tjwebb/pg-json-schema-export
https://github.com/tjwebb/pg-json-data-export

If those might approximately do what you need, let me know and we can collaborate.

**Comment by wingmanzz** [comment]
Our use case is a bit different--we need to go from some nasty csv to even nastier xml.

http://www.iatiregistry.org/

**Comment by tjwebb** [comment]
I'm going from postgres schema to Waterline ORM via JSON. I'm finding that just converting everything to JSON first makes everything easier, unless you have like terabytes of data or something. csv->json is easy, and json->xml is easy, for example.
